version: '3.8'

services:
  odoo:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: odoo-custom:19.0
    restart: unless-stopped
    ports:
      - "8069:8069"
    environment:
      HOST: host.docker.internal
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./docker/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./data/filestore:/var/lib/odoo/.local/share/Odoo/filestore
      - ./data/sessions:/var/lib/odoo/sessions
      - ./data/backups:/var/lib/odoo/backups
      - ./addons:/mnt/extra-addons
      - ./custom_addons:/mnt/custom-addons
    command: [
      "--config=/etc/odoo/odoo.conf",
      "--addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/CybroAddons,/mnt/custom-addons",
      "-d", "SGCTECHAI",
      "--logfile=/dev/stdout"
    ]
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  db-data:
